language: python
python:
  - "3.7"
# command to install dependencies
# env:
#   DB=sqlite
install:
  - python setup.py install
  - pip install coverage
  - pip install codecov
# command to run tests
git:
  depth: 50
jobs:
  include:
  - name: "django-project"
    python: "3.7"
script:
  - python -m coverage run manage.py test
after_success:
  - python -m codecov
