language: python
python:
  - "3.7"
# command to install dependencies
# env:
#   DB=sqlite
install:
  - python setup.py install
  # - pip install coverage
  # - pip install codecov
# command to run tests
git:
  depth: 50
jobs:
  include:
  - name: "django-project"
    python: "3.7"
script:
  - python -m isort --profile black .
  - python -m black .
  - python -m flake8 --ignore=E501,W503
  - python -m coverage run manage.py test
  - python -m coverage report --fail-under=80 --omit=*/python3.7/*,*/migrations/*
after_success:
  - python -m codecov
